version: '3'
services:
  fpm:
    build: ./fpm
    tty: true
    working_dir: /var/www/statistic
    volumes:
      - ../.:/var/www/statistic:cached
      - ./fpm/config/php.ini-local:/usr/local/etc/php/php.ini:ro

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/statistic
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/statistic:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=statistic
      - MYSQL_USER=statistic
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "8002:6379"

volumes:
  mysql_data:
